allow cancellation of call using dio cancellation
gql-dart/gql pull request #408
Opened 2023-07-07 06:48 UTC by rgplvr

allow cancellation of call using dio cancellation

2023-07-09 11:07 UTC, knaeckeKami commented
Hello, thanks for the PR. It seems there is an issue with the CI, looks like a breaking change in one of the dependencies of multipack. I'll try to fix it.

Support for cancellation in Dio is good, but is passing a signal cancel token for all requests of the link the right approach? 

You can only cancel the token once, right?

I think a better solution would be to pass the cancel token via the context. Then the client code could either create a new cancel token for each request or re-use the same token for multiple requests if preferred.


See e.g. https://github.com/gql-dart/gql/blob/master/links/gql_dio_link/lib/src/dio_link.dart#L312


```dart

class DioLinkCancelTokenContextEntry extends ContextEntry {

     final CancelToken token;

     ...
}
```
in DioLink:


```dart

...
final cancelToken = request.context.entry<DioLinkCancelTokenContextEntry>();

...

```

2023-07-09 14:30 UTC, rgplvr commented
Makes sense. I have made the changes to push the cancellation token to the context entry.

2023-07-23 14:46 UTC, knaeckeKami commented
please update your branch from master to fix the ci issues

2023-07-23 14:49 UTC, rgplvr commented
done

2023-07-23 14:52 UTC, knaeckeKami commented on links/gql_dio_link/lib/src/dio_link.dart
> +  // final dio.CancelToken? cancelToken;
pls delete commented leftover code

2023-07-23 14:54 UTC, knaeckeKami commented on links/gql_dio_link/lib/src/dio_link.dart
> +    final dio.Response<Map<String, dynamic>> dioResponse = await _executeDioRequest(
pls run `dart format`

2023-07-23 14:55 UTC, knaeckeKami requested changes
please delete the commented out code and run dart format

2023-07-23 15:03 UTC, rgplvr commented
made the changes the source is properly formatted as per the diff

2023-07-23 15:12 UTC, knaeckeKami approved these changes

2023-07-23 15:12 UTC, knaeckeKami commented
Thanks, LGTM

2023-07-23 15:12 UTC, merged